apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvcdag
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvclog
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi