
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: p-kowalik2-dev
subjects:
- kind: ServiceAccount
  name: scheduler 
  namespace: p-kowalik2-dev
roleRef:
  kind: Role
  name: airflow 
  apiGroup: rbac.authorization.k8s.io
  